name: Todo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todo-frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Build Angular app
        run: npm run build
      - name: Run Angular tests
        run: npm test -- --watch=false --browsers=ChromeHeadless

  build-backend:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ auth, config, eureka, gateway, notification, todo ]
    services:
      auth-db:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: auth
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      todo-db:
        image: postgres:15
        ports:
          - 5433:5432
        env:
          POSTGRES_DB: todo
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v4
      - name: Config JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Build with Maven
        run: mvn clean install --file ${{ matrix.service }}/pom.xml
      - name: Run tests
        run: mvn test --file ${{ matrix.service }}/pom.xml